__william_mantegna/blog_app/config/routes.rb
BlogApp::Application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :comments
  end

end

__william_mantegna/blog_app/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post

	validates :email, :content, :post_id, presence: true
end

__william_mantegna/blog_app/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	validates :title, :content, presence: true
end

__william_mantegna/blog_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(comment_params)
		@post.comments << @comment

		redirect_to post_path @post, notice: 'Comment created!'
	end

	private
	def comment_params
		params.require(:comment).permit(:content, :email, :post_id)
	end
end

__william_mantegna/blog_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
    
    @comment = Comment.new
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.create(post_params)
  	
  	redirect_to "/posts/#{@post.id}"
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	@post.update_attributes(post_params)

  	redirect_to "/posts/#{@post.id}"
  end

  def destroy
  	@post = Post.find(params[:id])

    @post.comments.each do |c|
      c.destroy
    end
  	@post.destroy

  	redirect_to root_path
  end

  private
  def post_params
  	params.require(:post).permit(:title, :content)
  end
end

__william_mantegna/blog_app/app/helpers/posts_helper.rb
module PostsHelper
end

__william_mantegna/blog_app/app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
<%= f.label :email %>
<%= f.text_field :email %><br />

<%= f.label :content %>
<%= f.text_area :content %><br />
<% end %>

__william_mantegna/blog_app/app/views/comments/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

__william_mantegna/blog_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

__william_mantegna/blog_app/app/views/posts/edit.html.erb
<h1>Edit a post</h1>

<h1>Create a new Post</h1>
<%= form_for @post do |form| %>
	<table>
		<tr>
			<td><%= form.label :title %></td>
			<td><%= form.text_field :title %></td>
		</tr>
		<tr>
			<td><%= form.label :content %></td>
			<td><%= form.text_area :content %></td>
		</tr>
	</table>
	
	<%= form.submit %>
<% end %>

__william_mantegna/blog_app/app/views/posts/index.html.erb
<h1>Bill's Blog_app</h1>

<table>
	<tr>
		<th>Title</th>
		<th>Content</th>
		<th>Links</th>
<% @posts.each do |p| %>
	<tr>
		<th><%= p.title %></th>
		<td><%= p.content %></td>
		<td>
			<%= link_to "View", post_path(p) %>
			<%= link_to "Edit", edit_post_path(p) %>
			<%= link_to "Destory", p, method: :delete, data: { confirm: "Are you sure?" } %>
		</td>
	</tr>
<% end %>
</table>

<p><%= link_to "Create a new post", new_post_path %></p>

<hr>
Page served at <%= Time.now %>

__william_mantegna/blog_app/app/views/posts/new.html.erb
<h1>Create a new Post</h1>
<%= form_for @post do |form| %>
	<table>
		<tr>
			<td><%= form.label :title %></td>
			<td><%= form.text_field :title %></td>
		</tr>
		<tr>
			<td><%= form.label :content %></td>
			<td><%= form.text_area :content %></td>
		</tr>
	</table>
	
	<%= form.submit %>
<% end %>

__william_mantegna/blog_app/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<%= link_to "Home", root_path %>

<hr />

<h3>Comments</h3>
<% @post.comments.each do |c| %>
	<p><b><%= c.email %>:</b> <%= c.content %></p>
<% end%>
<br />


<div style="background-color:#bbb; width: 250px; padding: 10px">
<b style="font-size: 18px; text-align: center">Add a Comment</b>
<%= form_for [@post, @comment] do |f| %>
	
	<b><%= f.label :email %></b>
	<%= f.text_field :email %><br />

	<b><%= f.label :content %></b>
	<%= f.text_area :content %><br />

	<%= f.submit %>
<% end %>
</div>