__william_mantegna/fermently/config/routes.rb
Fermently::Application.routes.draw do
  
  devise_for :users
  resources :beer_styles
  resources :beers

  get "/about.html", to: "home#about"
  root "home#index"

end

__william_mantegna/fermently/app/models/beer.rb
class Beer < ActiveRecord::Base
	validates :name, :beer_style_id, :dateBrewed, presence: true
	belongs_to :beer_style
end

__william_mantegna/fermently/app/models/beer_style.rb
class BeerStyle < ActiveRecord::Base
	has_many :beers
end

__william_mantegna/fermently/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }#,
  #:format => { ... } # etc.
  # I THINK THIS IS WHERE THE ERROR IS

  #where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first


  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
  

  def self.find_first_by_auth_conditions(warden_conditions)
   conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

__william_mantegna/fermently/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  attr_accessor :login

  before_filter :configure_permitted_parameters, if: :devise_controller?


  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

__william_mantegna/fermently/app/controllers/beer_styles_controller.rb
class BeerStylesController < ApplicationController
  
  before_action :set_beer_style, only: [:show, :edit, :update, :destroy]

  def index
  	@beerStyles = BeerStyle.all.order("lower(name) asc")
  end

  def show
    @beers = @beerStyle.beers.order(rating: :desc)
  end

  def new
  	@beerStyle = BeerStyle.new
  end

  def create
  	@beerStyle = BeerStyle.create(beer_style_params)
  	
  	if @beerStyle.save
  		redirect_to "/beer_styles/#{@beerStyle.id}"
  	else
  		flash[:error] = "Something went wrong!"
  		redirect_to new_beer_style_path
  	end
  end

  def edit
  end

  def update
  	@beerStyle.update_attributes(beer_style_params)
  	redirect_to "/beer_styles/#{@beerStyle.id}"
  end

  def destroy
  	@beerStyle.destroy
  	redirect_to beer_styles_path
  end

  private
  def beer_style_params
  	params.require(:beer_style).permit(:name, :category, :description, :abvMin, :abvMax, :ibuMin, :ibuMax, :ogMin, :ogMax, :fgMin, :fgMax, :srmMin, :srmMax)
  end

  def set_beer_style
    @beerStyle = BeerStyle.find(params[:id])
  end
end

__william_mantegna/fermently/app/controllers/beers_controller.rb
class BeersController < ApplicationController
  
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  def index
  	@beers = Beer.all.order(dateBrewed: :desc)
  end

  def new
  	@beer = Beer.new
    @beer_styles = BeerStyle.all
  end

  def create
    @beer = Beer.create(beer_params)

    if @beer.save
      redirect_to "/beers/#{@beer.id}", notice: "Beer Successfully Created!"
    else
      flash[:error] = "Something went wrong! Please double-check your records."
      redirect_to new_beer_path
    end
  end

  def show
  end

  def edit
  end

  def update
  	@beer.update_attributes(beer_params)
    redirect_to beer_path
  end

  def destroy
    @beer.destroy
    redirect_to beers_path
  end

  private
  def beer_params
  	params.require(:beer).permit(:id, :name, :beer_style_id, :og, :fg, :abv, :dateBrewed, :dateBottled, :priming, :recipe, :rating, :brewerComment)
  end

  def set_beer
    @beer = Beer.find(params[:id])
  end
end

__william_mantegna/fermently/app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
	
end

__william_mantegna/fermently/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def about
	end
end

__william_mantegna/fermently/app/helpers/application_helper.rb
module ApplicationHelper
end

__william_mantegna/fermently/app/views/beer_styles/edit.html.erb
<h1>Edit a Beer Style</h1>

<%= form_for @beerStyle do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br />

	<%= f.label :category %>
	<%= f.text_field :category %><br />

	<%= f.label :description %>
	<%= f.text_field :description %><br />

	<%= f.label :abvMin %>
	<%= f.text_field :abvMin %><br />

	<%= f.label :abvMax %>
	<%= f.text_field :abvMax %><br />

	<%= f.label :ibuMin %>
	<%= f.text_field :ibuMin %><br />

	<%= f.label :ibuMax %>
	<%= f.text_field :ibuMax %><br />

	<%= f.label :ogMin %>
	<%= f.text_field :ogMin %><br />

	<%= f.label :ogMax %>
	<%= f.text_field :ogMax %><br />

	<%= f.label :fgMin %>
	<%= f.text_field :fgMin %><br />

	<%= f.label :fgMax %>
	<%= f.text_field :fgMax %><br />

	<%= f.label :srmMin %>
	<%= f.text_field :srmMin %><br />

	<%= f.label :srmMax %>
	<%= f.text_field :srmMax %><br />

	<%= f.submit %>
<% end %>

__william_mantegna/fermently/app/views/beer_styles/index.html.erb
<h1>BeerStyles#index</h1>
<p>Find me in app/views/beer_styles/indexs.html.erb</p>

<table border="1" cellpadding="5">
	<tr>
		<th>Name</th>
		<th>Category</th>
		<th>abvMin</th>
		<th>abvMax</th>
		<th>ibuMin</th>
		<th>ibuMax</th>
		<th>Created at</th>
		<th>Updated at</th>
		<th>Links</th>
	</tr>
<% @beerStyles.each do |bs| %>
	<tr>
		<td><%= bs.name %></td>
		<td><%= bs.category %></td>
		<td><%= bs.abvMin %></td>
		<td><%= bs.abvMax %></td>
		<td><%= bs.ibuMin %></td>
		<td><%= bs.ibuMax %></td>
		<td><%= bs.created_at %></td>
		<td><%= bs.updated_at %></td>
		<td>
			<%= link_to "Show", beer_style_path(bs) %> | 
			<%= link_to "Edit", edit_beer_style_path(bs) %> | 
			<%= link_to "Destroy", beer_style_path(bs), method: :delete, data: {confirm: "Are you sure?"} %>
		</td>
	</tr>
<% end %>
</table>
<p><%= link_to "Add a Beer Style", new_beer_style_path %></p>
<p><%= link_to "View List of Beers", beers_path %></p>

__william_mantegna/fermently/app/views/beer_styles/new.html.erb
<h1>Add a Beer Style</h1>

<%= form_for @beerStyle do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br />

	<%= f.label :category %>
	<%= f.text_field :category %><br />

	<%= f.label :description %>
	<%= f.text_field :description %><br />

	<%= f.label :abvMin %>
	<%= f.text_field :abvMin %><br />

	<%= f.label :abvMax %>
	<%= f.text_field :abvMax %><br />

	<%= f.label :ibuMin %>
	<%= f.text_field :ibuMin %><br />

	<%= f.label :ibuMax %>
	<%= f.text_field :ibuMax %><br />

	<%= f.label :ogMin %>
	<%= f.text_field :ogMin %><br />

	<%= f.label :ogMax %>
	<%= f.text_field :ogMax %><br />

	<%= f.label :fgMin %>
	<%= f.text_field :fgMin %><br />

	<%= f.label :fgMax %>
	<%= f.text_field :fgMax %><br />

	<%= f.label :srmMin %>
	<%= f.text_field :srmMin %><br />

	<%= f.label :srmMax %>
	<%= f.text_field :srmMax %><br />


	<%= f.submit %>
<% end %>

<p><%= link_to "Back to list of Beer Styles", beer_styles_path %></p>

__william_mantegna/fermently/app/views/beer_styles/show.html.erb
<h1><%= @beerStyle.name %></h1>

<table>
	<tr>
		<th>Category</th>
		<td><%= @beerStyle.category %></td>
	</tr>
	<tr>
		<th>description</th>
		<td><%= @beerStyle.description %></td>
	</tr>
	<tr>
		<th>abvMin</th>
		<td><%= @beerStyle.abvMin %></td>
	</tr>
	<tr>
		<th>abvMax</th>
		<td><%= @beerStyle.abvMax %></td>
	</tr>
	<tr>
		<th>ibuMin</th>
		<td><%= @beerStyle.ibuMin %></td>
	</tr>
	<tr>
		<th>ibuMax</th>
		<td><%= @beerStyle.ibuMax %></td>
	</tr>
	<tr>
		<th>ogMin</th>
		<td><%= @beerStyle.ogMin %></td>
	</tr>
	<tr>
		<th>ogMax</th>
		<td><%= @beerStyle.ogMax %></td>
	</tr>
	<tr>
		<th>fgMin</th>
		<td><%= @beerStyle.fgMin %></td>
	</tr>
	<tr>
		<th>fgMax</th>
		<td><%= @beerStyle.fgMax %></td>
	</tr>
	<tr>
		<th>srmMin</th>
		<td><%= @beerStyle.srmMin %></td>
	</tr>
	<tr>
		<th>srmMax</th>
		<td><%= @beerStyle.srmMax %></td>
	</tr>
	<tr>
		<th>Created At</th>
		<td><%= @beerStyle.created_at %></td>
	</tr>
	<tr>
		<th>Updated At</th>
		<td><%= @beerStyle.updated_at %></td>
	</tr>
</table>
<p><%= link_to "Edit This Style", edit_beer_style_path %><br />
<%= link_to "Beer Styles Home", beer_styles_path %></p>
<br />
<h2>Homebrews made with this style</h2>
<table cellpadding="5" border="1">
	<tr>
		<th>Name</th>
		<th>Rating</th>
		<th>abv</th>
		<th>OG</th>
		<th>FG</th>
		<th>Date Brewed</th>
		<th>Date Bottled</th>
		<th>Priming</th>
		<th>Links</th>
	</tr>
<% @beers.each do |b| %>
	<tr>
		<td><%= b.name %></td>
		<td><%= b.rating %></td>
		<td><%= b.abv %></td>
		<td><%= b.og %></td>
		<td><%= b.fg %></td>
		<td><%= b.dateBrewed %></td>
		<td><%= b.dateBottled %></td>
		<td><%= b.priming %></td>
		<td>
			<%= link_to "Show", beer_path(b) %> | 
			<%= link_to "Edit", edit_beer_path(b) %> | 
			<%= link_to "Delete", b, method: :delete %>
		</td>
	</tr>
<% end %>
</table>


<p><%= link_to "Beers Home", beers_path %></p>

__william_mantegna/fermently/app/views/beers/edit.html.erb
<h1>Beers#edit</h1>
<p>Find me in app/views/beers/edit.html.erb</p>


<%= form_for @beer do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br />

	<%= f.label :beer_style %>
	
	<%= f.collection_select :beer_style_id, BeerStyle.all, :id, :name, prompt: "Beer Style" %><br />
	<%= f.label :recipe %>
	<%= f.text_field :recipe %><br />
	<%= f.label :og %>
	<%= f.text_field :og %><br />
	<%= f.label :fg %>
	<%= f.text_field :fg %><br />
	<%= f.label :abv %>
	<%= f.text_field :abv %><br />
	<%= f.label :dateBrewed %>
	<%= f.date_field :dateBrewed %><br />
	<%= f.label :dateBottled %>
	<%= f.date_field :dateBottled %><br />
	<%= f.label :priming %>
	<%= f.text_field :priming %><br />
	<%= f.label :rating %>
	<%= f.text_field :rating %><br />
	<%= f.label :brewerComment %>
	<%= f.text_field :brewerComment %><br />

	<%= f.submit %>
<% end %>	
<br />
<%= link_to "Back to list of beers", beers_path %>

__william_mantegna/fermently/app/views/beers/index.html.erb
<h1>Beers#index</h1>
<p>Find me in app/views/beers/index.html.erb</p>
<table cellpadding="5" border="1">
	<tr>
		<th>Name</th>
		<th>Style</th>
		<th>OG</th>
		<th>FG</th>
		<th>abv</th>
		<th>Date Brewed</th>
		<th>Date Bottled</th>
		<th>Priming</th>
		<th>Brewer Rating</th>
		<th>Links</th>
	</tr>
<% @beers.each do |b| %>
	<tr>
		<td><%= b.name %></td>
		<td><%= b.beer_style.name %></td>
		<td><%= b.og %></td>
		<td><%= b.fg %></td>
		<td><%= b.abv %></td>
		<td><%= b.dateBrewed %></td>
		<td><%= b.dateBottled %></td>
		<td><%= b.priming %></td>
		<td><%= b.rating %></td>
		<td>
			<%= link_to "Show", beer_path(b) %> | 
			<%= link_to "Edit", edit_beer_path(b) %> | 
			<%= link_to "Delete", b, method: :delete %>
		</td>
	</tr>
<% end %>
</table>

<p><%= link_to "Add a beer", new_beer_path %></p>
<p><%= link_to "View Beer Styles", beer_styles_path %></p>

__william_mantegna/fermently/app/views/beers/new.html.erb
<h1>Add a Beer</h1>

<%= form_for @beer do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br />

	<%= f.label :beer_style %>
	
	<%= f.collection_select :beer_style_id, BeerStyle.all, :id, :name, prompt: "Beer Style" %><br />
	<%= f.label :recipe %>
	<%= f.text_field :recipe %><br />
	<%= f.label :og %>
	<%= f.text_field :og %><br />
	<%= f.label :fg %>
	<%= f.text_field :fg %><br />
	<%= f.label :abv %>
	<%= f.text_field :abv %><br />
	<%= f.label :dateBrewed %>
	<%= f.date_field :dateBrewed %><br />
	<%= f.label :dateBottled %>
	<%= f.date_field :dateBottled %><br />
	<%= f.label :priming %>
	<%= f.text_field :priming %><br />
	<%= f.label :rating %>
	<%= f.text_field :rating %><br />
	<%= f.label :brewerComment %>
	<%= f.text_field :brewerComment %><br />

	<%= f.submit %>
<% end %>
<p><%= link_to "Back To List of Beers", beers_path %></p>

__william_mantegna/fermently/app/views/beers/show.html.erb
<h1>Beers#show</h1>
<p>Find me in app/views/beers/show.html.erb</p>


<b>Name:</b> <%= @beer.name %><br />
<b>Beer Style:</b> <%= link_to @beer.beer_style.name, beer_style_path(@beer.beer_style) %><br />
<b>Recipe:</b> <%= @beer.recipe %><br />
<b>OG:</b> <%= @beer.og %><br />
<b>FG:</b> <%= @beer.fg %><br />
<b>ABV:</b> <%= @beer.abv %><br />
<b>Date Brewed:</b> <%= @beer.dateBrewed %><br />
<b>Date Bottled:</b> <%= @beer.dateBottled %><br />
<b>Priming:</b> <%= @beer.priming %><br />
<b>Rating:</b> <%= @beer.rating %><br />
<b>Brewer Comment:</b> <%= @beer.brewerComment %><br />
<b>Created At:</b> <%= @beer.created_at %><br />
<b>Updated At:</b> <%= @beer.updated_at %><br />
<br />
<p><%= link_to "Edit Beer", edit_beer_path %></p>
<p><%= link_to "List of All Beer", beers_path %></p>

__william_mantegna/fermently/app/views/home/about.html.erb
<p align="center">I have a dream,<br /> that one day, brewers everywhere<br /> will be able to easily share data about their brews<br /> across the World Wide Web!</p>
<hr width=75% />
<p>These were the words written down by our Fearless Fermentin' Leader on that fateful day in December 2013. Simply, we want to help you homebrew! And maybe brag to your friends about your successes...but hey! All is fair in love and war? Right?</p>

<p>This is an ongoing project. Here is some info about the development process:</p>
<ul>
	<li>CRUD for Beer Styles (COMPLETE)</li>
	<li>CRUD for Beers (COMPLETE)</li>
	<li>Homepage with basic menu (COMPLETE)</li>
	<li>CRUD for Users (ongoing)</li>
	<li>beers belong_to_and_have_many users (tbd)</li>
</ul>

__william_mantegna/fermently/app/views/home/index.html.erb
<h1>Welcome to Fermently!</h1>

<div style="background-color:teal; width: 250px; text-align: center">
<% if user_signed_in? %>
	Sweet! You're already logged in!
<% else %>
	If you haven't done so already, please sign up to add some homebrewin' data of your own!
<% end %>
</div>
	<ol>
		<li class="complete">As a user, I want to be able to see a list of beer styles.</li>
		<li class="complete">As a user, I want to be able to add a beer and it's related data to the website.</li>
		<li class="complete">As a user, I want to have my own account.</li>
		<li>As a user, I want to be able to log in using my email address or my username.</li>
		<li>As a user, I want to have my own profile page.</li>
			<ul>
				<li>fermently.com/username</li>
			</uL>
		<li>As a user, I want to connect beers to my profile.</li>
		<li>As a user, I want to be able to see my friends homebrewing data.</li>
		<li>As a user, I want to be able to be friends with other profiles.</li>
		<li>As a user, I want to be able to see averages of metrics for specific beers listed on it's beer style page.</li>
		<li></li>
		<li>As a user, I want to be able eat bacon and bagels with cream cheese.</li>
	</ol>

__william_mantegna/fermently/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fermently</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<table width=100% cellspacing=0>
		<tr>
			<td>
				<h1>Fermently</h1>
				<%= link_to "Home", root_path %> | 
				<%= link_to "Beers", beers_path %> | 
				<%= link_to "Beer Styles", beer_styles_path %> | 
				<%= link_to "About us", "/about.html" %>
			</td>
			<td>
				<div align="right">
					<br />
					<br />
					
					<% if user_signed_in? %>	
						<br />
						Hello <%= current_user.email %> | <%= current_user.id %><br />
						<%= link_to "Log out", destroy_user_session_path, method: :delete %>
					<% else %>
						<%= link_to "Login", new_user_session_path %><br />	
						<%= link_to "Sign up", new_user_registration_path %>
					<% end %>

				</div>
			</td>
		</tr>
	</table>
	<hr />
</header>

<p style="color:red;"><%= flash[:error] %></p>
<p style="color:green;"><%= notice %></p>
<p class="color:red;"><%= alert %></p>

<%= yield %>

</body>
</html>

__william_mantegna/fermently/app/views/users/edit.html.erb
<h1>Edit your profile Information</h1>

__william_mantegna/fermently/app/views/users/index.html.erb
<h1>List of all users</h1>